### ISSUE TITLE
Add button for setting vis as intent

### ISSUE THREAD

**Issue by dorisjlee** [lux-org/lux-widget#30]
To set a visualization as the intent, users currently have to export a visualization of interest and then save it as a variable, then reset it as the intent: 

```
vis = df.get_exported()[0]
df.intent = vis
df
```
We should add a button that automatically sets the intent as the selected visualization.

**Comment by cjachekang** [comment]
Did you want the widget to change to the intent view automatically(I think this will probably require restarting the widget)? Or keep the previous behavior where you needed to run a cell with `df` shown in the gif below. 

![zSQqMeSuuY](https://user-images.githubusercontent.com/47467363/95396251-5bf7c780-08b5-11eb-8eaf-0b409455cabf.gif)

**Comment by dorisjlee** [comment]
Resolved in #48.
