### ISSUE TITLE
Jupyter Lab 3 support

### ISSUE THREAD

**Issue by dorisjlee** [lux-org/lux-widget#64]
Supporting lux-widget for newly-released Jupyter Lab 3

**Comment by dorisjlee** [comment]
Binder also uses jupyterlab 3.0.7, so currently the Jupyter Lab version on Binder is not working
<img src="https://user-images.githubusercontent.com/5554675/108501522-635fc080-72ec-11eb-96a6-9e9b243c0948.png" width="400">

**Comment by fabbber** [comment]
same problem here
