### ISSUE TITLE
Vislist UI is overcrowded and not rendering properly

### ISSUE THREAD

**Issue by willeppy** [lux-org/lux-widget#85]
It seems like when the current vis is a VisList, the widget UI is not rendering properly and has overlapping elements in the top left corner, see the screenshot below from the binder

Lux version: 0.3.0
luxwidget version: 0.1.5

<img width="1153" alt="Screen Shot 2021-05-07 at 12 58 48 PM" src="https://user-images.githubusercontent.com/13400543/117483680-027f7600-af34-11eb-9d0d-3d1662f7a739.png">

**Comment by dorisjlee** [comment]
Thanks for reporting this issue @willeppy! This does seem like a bug since the current vis should not be there. I'll look into fixing this soon!

**Comment by dorisjlee** [comment]
I just pushed a fix to this, thanks @willeppy!
